### ISSUE TITLE
Exception thrown in UnicodeJsps/bidi.jsp

### ISSUE THREAD

**Issue by macchiati** [unicode-org/unicodetools#274]
Relaying the following report:

While experimenting with explicit directional isolates with the utilities hosted at https://util.unicode.org/UnicodeJsps/bidi.jsp, I found that use of them with the bidi utility causes a java.lang.ArrayIndexOutOfBoundsException to be thrown from org.unicode.jsp.BidiCharMap.getBidiClass(BidiCharMap.java:84). The sample text I am using is print("⁧hi⁩") where U+2067 (RLI) precedes hi and U+2069 (PDI) follows it. The problem should reproduce with https://util.unicode.org/UnicodeJsps/bidi.jsp?a=print%28%22%E2%81%A7hi%E2%81%A9%22%29&p=Auto.

The diagnostic page that is generated follows:

<h2>HTTP ERROR 500 javax.servlet.ServletException: 

org.apache.jasper.JasperException: An exception occurred processing 

[/bidi.jsp] at line [81]

78: &lt;input type="checkbox" &lt;%=hack ? "checked" : ""%&gt; 

name="hack"&gt;&lt;label for="hack"&gt;ASCII Hack?&lt;/label&gt;

79: &lt;input id='main' type="submit" value="Show Bidi" 

onClick="window.location.href='transform.jsp?a='+document.getElementById('main').value"/&gt;

80:   &lt;hr&gt;

81:   &lt;%= UnicodeJsp.showBidi(sample, p2, hack)%&gt;

82: &lt;/form&gt;

83: &lt;%@ include file="footer.jsp" %&gt;

84: &lt;/body&gt;

Stacktrace:</h2>

URI: | /UnicodeJsps/bidi.jsp

-- | --

500

javax.servlet.ServletException:  org.apache.jasper.JasperException: An exception occurred processing  [/bidi.jsp] at line [81]  78: <input type="checkbox" <%=hack ? "checked" : ""%>  name="hack"><label for="hack">ASCII Hack?</label> 79: <input id='main' type="submit" value="Show Bidi"  onClick="window.location.href='transform.jsp?a='+document.getElementById('main').value"/> 80:   <hr> 81:   <%= UnicodeJsp.showBidi(sample, p2, hack)%> 82: </form> 83: <%@ include file="footer.jsp" %> 84: </body>   Stacktrace:

jsp

javax.servlet.ServletException:  org.apache.jasper.JasperException: An exception occurred processing  [/bidi.jsp] at line [81]  78: <input type="checkbox" <%=hack ? "checked" : ""%>  name="hack"><label for="hack">ASCII Hack?</label> 79: <input id='main' type="submit" value="Show Bidi"  onClick="window.location.href='transform.jsp?a='+document.getElementById('main').value"/> 80:   <hr> 81:   <%= UnicodeJsp.showBidi(sample, p2, hack)%> 82: </form> 83: <%@ include file="footer.jsp" %> 84: </body>   Stacktrace:

org.apache.jasper.JasperException: An  exception occurred processing [/bidi.jsp] at line [81]  78: <input type="checkbox" <%=hack ? "checked" : ""%>  name="hack"><label for="hack">ASCII Hack?</label> 79: <input id='main' type="submit" value="Show Bidi"  onClick="window.location.href='transform.jsp?a='+document.getElementById('main').value"/> 80:   <hr> 81:   <%= UnicodeJsp.showBidi(sample, p2, hack)%> 82: </form> 83: <%@ include file="footer.jsp" %> 84: </body>   Stacktrace:

java.lang.ArrayIndexOutOfBoundsException: Index 21 out of bounds for length 19

<h3>Caused by:</h3><pre>javax.servlet.ServletException: org.apache.jasper.JasperException: An exception occurred processing [/bidi.jsp] at line [81]

78: &lt;input type="checkbox" &lt;%=hack ? "checked" : ""%&gt; name="hack"&gt;&lt;label for="hack"&gt;ASCII Hack?&lt;/label&gt;

79: &lt;input id='main' type="submit" value="Show Bidi" onClick="window.location.href='transform.jsp?a='+document.getElementById('main').value"/&gt;

80:   &lt;hr&gt;

81:   &lt;%= UnicodeJsp.showBidi(sample, p2, hack)%&gt;

82: &lt;/form&gt;

83: &lt;%@ include file="footer.jsp" %&gt;

84: &lt;/body&gt;

Stacktrace:

	at org.eclipse.jetty.server.handler.HandlerCollection.handle(HandlerCollection.java:162)

	at org.eclipse.jetty.server.handler.HandlerWrapper.handle(HandlerWrapper.java:127)

	at org.eclipse.jetty.server.Server.handle(Server.java:516)

	at org.eclipse.jetty.server.HttpChannel.lambda$handle$1(HttpChannel.java:400)

	at org.eclipse.jetty.server.HttpChannel.dispatch(HttpChannel.java:645)

	at org.eclipse.jetty.server.HttpChannel.handle(HttpChannel.java:392)

	at org.eclipse.jetty.server.HttpConnection.onFillable(HttpConnection.java:277)

	at org.eclipse.jetty.io.AbstractConnection$ReadCallback.succeeded(AbstractConnection.java:311)

	at org.eclipse.jetty.io.FillInterest.fillable(FillInterest.java:105)

	at org.eclipse.jetty.io.ChannelEndPoint$1.run(ChannelEndPoint.java:104)

	at org.eclipse.jetty.util.thread.strategy.EatWhatYouKill.runTask(EatWhatYouKill.java:338)

	at org.eclipse.jetty.util.thread.strategy.EatWhatYouKill.doProduce(EatWhatYouKill.java:315)

	at org.eclipse.jetty.util.thread.strategy.EatWhatYouKill.tryProduce(EatWhatYouKill.java:173)

	at org.eclipse.jetty.util.thread.strategy.EatWhatYouKill.run(EatWhatYouKill.java:131)

	at org.eclipse.jetty.util.thread.ReservedThreadExecutor$ReservedThread.run(ReservedThreadExecutor.java:409)

	at org.eclipse.jetty.util.thread.QueuedThreadPool.runJob(QueuedThreadPool.java:883)

	at org.eclipse.jetty.util.thread.QueuedThreadPool$Runner.run(QueuedThreadPool.java:1034)

	at java.base/java.lang.Thread.run(Unknown Source)

Caused by: org.apache.jasper.JasperException: An exception occurred processing [/bidi.jsp] at line [81]

78: &lt;input type="checkbox" &lt;%=hack ? "checked" : ""%&gt; name="hack"&gt;&lt;label for="hack"&gt;ASCII Hack?&lt;/label&gt;

79: &lt;input id='main' type="submit" value="Show Bidi" onClick="window.location.href='transform.jsp?a='+document.getElementById('main').value"/&gt;

80:   &lt;hr&gt;

81:   &lt;%= UnicodeJsp.showBidi(sample, p2, hack)%&gt;

82: &lt;/form&gt;

83: &lt;%@ include file="footer.jsp" %&gt;

84: &lt;/body&gt;

Stacktrace:

	at org.apache.jasper.servlet.JspServletWrapper.handleJspException(JspServletWrapper.java:601)

	at org.apache.jasper.servlet.JspServletWrapper.service(JspServletWrapper.java:498)

	at org.apache.jasper.servlet.JspServlet.serviceJspFile(JspServlet.java:383)

	at org.apache.jasper.servlet.JspServlet.service(JspServlet.java:331)

	at org.eclipse.jetty.jsp.JettyJspServlet.service(JettyJspServlet.java:106)

	at javax.servlet.http.HttpServlet.service(HttpServlet.java:790)

	at org.eclipse.jetty.servlet.ServletHolder$NotAsync.service(ServletHolder.java:1450)

	at org.eclipse.jetty.servlet.ServletHolder.handle(ServletHolder.java:799)

	at org.eclipse.jetty.servlet.ServletHandler$ChainEnd.doFilter(ServletHandler.java:1631)

	at org.eclipse.jetty.websocket.server.WebSocketUpgradeFilter.doFilter(WebSocketUpgradeFilter.java:228)

	at org.eclipse.jetty.servlet.FilterHolder.doFilter(FilterHolder.java:193)

	at org.eclipse.jetty.servlet.ServletHandler$Chain.doFilter(ServletHandler.java:1601)

	at org.eclipse.jetty.servlet.ServletHandler.doHandle(ServletHandler.java:548)

	at org.eclipse.jetty.server.handler.ScopedHandler.handle(ScopedHandler.java:143)

	at org.eclipse.jetty.security.SecurityHandler.handle(SecurityHandler.java:600)

	at org.eclipse.jetty.server.handler.HandlerWrapper.handle(HandlerWrapper.java:127)

	at org.eclipse.jetty.server.handler.ScopedHandler.nextHandle(ScopedHandler.java:235)

	at org.eclipse.jetty.server.session.SessionHandler.doHandle(SessionHandler.java:1624)

	at org.eclipse.jetty.server.handler.ScopedHandler.nextHandle(ScopedHandler.java:233)

	at org.eclipse.jetty.server.handler.ContextHandler.doHandle(ContextHandler.java:1434)

	at org.eclipse.jetty.server.handler.ScopedHandler.nextScope(ScopedHandler.java:188)

	at org.eclipse.jetty.servlet.ServletHandler.doScope(ServletHandler.java:501)

	at org.eclipse.jetty.server.session.SessionHandler.doScope(SessionHandler.java:1594)

	at org.eclipse.jetty.server.handler.ScopedHandler.nextScope(ScopedHandler.java:186)

	at org.eclipse.jetty.server.handler.ContextHandler.doScope(ContextHandler.java:1349)

	at org.eclipse.jetty.server.handler.ScopedHandler.handle(ScopedHandler.java:141)

	at org.eclipse.jetty.server.handler.ContextHandlerCollection.handle(ContextHandlerCollection.java:234)

	at org.eclipse.jetty.server.handler.HandlerCollection.handle(HandlerCollection.java:146)

	... 17 more

Caused by: java.lang.ArrayIndexOutOfBoundsException: Index 21 out of bounds for length 19

	at org.unicode.jsp.BidiCharMap.getBidiClass(BidiCharMap.java:84)

	at org.unicode.jsp.BidiCharMap.getBidiClass(BidiCharMap.java:88)

	at org.unicode.jsp.UnicodeUtilities.showBidiLine(UnicodeUtilities.java:1630)

	at org.unicode.jsp.UnicodeUtilities.showBidi(UnicodeUtilities.java:1597)

	at org.unicode.jsp.UnicodeJsp.showBidi(UnicodeJsp.java:37)

	at org.apache.jsp.bidi_jsp._jspService(bidi_jsp.java:278)

	at org.apache.jasper.runtime.HttpJspBase.service(HttpJspBase.java:70)

	at javax.servlet.http.HttpServlet.service(HttpServlet.java:790)

	at org.apache.jasper.servlet.JspServletWrapper.service(JspServletWrapper.java:465)

	... 43 more

</pre>

<hr><a href="https://eclipse.org/jetty">Powered by Jetty:// 9.4.44.v20210927</a><hr>

HTTP ERROR 500 javax.servlet.ServletException: org.apache.jasper.JasperException: An exception occurred processing [/bidi.jsp] at line [81] 78: <input type="checkbox" <%=hack ? "checked" : ""%> name="hack"><label for="hack">ASCII Hack?</label> 79: <input id='main' type="submit" value="Show Bidi" onClick="window.location.href='transform.jsp?a='+document.getElementById('main').value"/> 80: <hr> 81: <%= UnicodeJsp.showBidi(sample, p2, hack)%> 82: </form> 83: <%@ include file="footer.jsp" %> 84: </body> Stacktrace:

URI:	/UnicodeJsps/bidi.jsp

STATUS:	500

MESSAGE:	javax.servlet.ServletException: org.apache.jasper.JasperException: An exception occurred processing [/bidi.jsp] at line [81] 78: <input type="checkbox" <%=hack ? "checked" : ""%> name="hack"><label for="hack">ASCII Hack?</label> 79: <input id='main' type="submit" value="Show Bidi" onClick="window.location.href='transform.jsp?a='+document.getElementById('main').value"/> 80: <hr> 81: <%= UnicodeJsp.showBidi(sample, p2, hack)%> 82: </form> 83: <%@ include file="footer.jsp" %> 84: </body> Stacktrace:

SERVLET:	jsp

CAUSED BY:	javax.servlet.ServletException: org.apache.jasper.JasperException: An exception occurred processing [/bidi.jsp] at line [81] 78: <input type="checkbox" <%=hack ? "checked" : ""%> name="hack"><label for="hack">ASCII Hack?</label> 79: <input id='main' type="submit" value="Show Bidi" onClick="window.location.href='transform.jsp?a='+document.getElementById('main').value"/> 80: <hr> 81: <%= UnicodeJsp.showBidi(sample, p2, hack)%> 82: </form> 83: <%@ include file="footer.jsp" %> 84: </body> Stacktrace:

CAUSED BY:	org.apache.jasper.JasperException: An exception occurred processing [/bidi.jsp] at line [81] 78: <input type="checkbox" <%=hack ? "checked" : ""%> name="hack"><label for="hack">ASCII Hack?</label> 79: <input id='main' type="submit" value="Show Bidi" onClick="window.location.href='transform.jsp?a='+document.getElementById('main').value"/> 80: <hr> 81: <%= UnicodeJsp.showBidi(sample, p2, hack)%> 82: </form> 83: <%@ include file="footer.jsp" %> 84: </body> Stacktrace:

CAUSED BY:	java.lang.ArrayIndexOutOfBoundsException: Index 21 out of bounds for length 19

Caused by:

javax.servlet.ServletException: org.apache.jasper.JasperException: An exception occurred processing [/bidi.jsp] at line [81]

78: <input type="checkbox" <%=hack ? "checked" : ""%> name="hack"><label for="hack">ASCII Hack?</label>

79: <input id='main' type="submit" value="Show Bidi" onClick="window.location.href='transform.jsp?a='+document.getElementById('main').value"/>

80:   <hr>

81:   <%= UnicodeJsp.showBidi(sample, p2, hack)%>

82: </form>

83: <%@ include file="footer.jsp" %>

84: </body>

Stacktrace:

	at org.eclipse.jetty.server.handler.HandlerCollection.handle(HandlerCollection.java:162)

	at org.eclipse.jetty.server.handler.HandlerWrapper.handle(HandlerWrapper.java:127)

	at org.eclipse.jetty.server.Server.handle(Server.java:516)

	at org.eclipse.jetty.server.HttpChannel.lambda$handle$1(HttpChannel.java:400)

	at org.eclipse.jetty.server.HttpChannel.dispatch(HttpChannel.java:645)

	at org.eclipse.jetty.server.HttpChannel.handle(HttpChannel.java:392)

	at org.eclipse.jetty.server.HttpConnection.onFillable(HttpConnection.java:277)

	at org.eclipse.jetty.io.AbstractConnection$ReadCallback.succeeded(AbstractConnection.java:311)

	at org.eclipse.jetty.io.FillInterest.fillable(FillInterest.java:105)

	at org.eclipse.jetty.io.ChannelEndPoint$1.run(ChannelEndPoint.java:104)

	at org.eclipse.jetty.util.thread.strategy.EatWhatYouKill.runTask(EatWhatYouKill.java:338)

	at org.eclipse.jetty.util.thread.strategy.EatWhatYouKill.doProduce(EatWhatYouKill.java:315)

	at org.eclipse.jetty.util.thread.strategy.EatWhatYouKill.tryProduce(EatWhatYouKill.java:173)

	at org.eclipse.jetty.util.thread.strategy.EatWhatYouKill.run(EatWhatYouKill.java:131)

	at org.eclipse.jetty.util.thread.ReservedThreadExecutor$ReservedThread.run(ReservedThreadExecutor.java:409)

	at org.eclipse.jetty.util.thread.QueuedThreadPool.runJob(QueuedThreadPool.java:883)

	at org.eclipse.jetty.util.thread.QueuedThreadPool$Runner.run(QueuedThreadPool.java:1034)

	at java.base/java.lang.Thread.run(Unknown Source)

Caused by: org.apache.jasper.JasperException: An exception occurred processing [/bidi.jsp] at line [81]

78: <input type="checkbox" <%=hack ? "checked" : ""%> name="hack"><label for="hack">ASCII Hack?</label>

79: <input id='main' type="submit" value="Show Bidi" onClick="window.location.href='transform.jsp?a='+document.getElementById('main').value"/>

80:   <hr>

81:   <%= UnicodeJsp.showBidi(sample, p2, hack)%>

82: </form>

83: <%@ include file="footer.jsp" %>

84: </body>

Stacktrace:

	at org.apache.jasper.servlet.JspServletWrapper.handleJspException(JspServletWrapper.java:601)

	at org.apache.jasper.servlet.JspServletWrapper.service(JspServletWrapper.java:498)

	at org.apache.jasper.servlet.JspServlet.serviceJspFile(JspServlet.java:383)

	at org.apache.jasper.servlet.JspServlet.service(JspServlet.java:331)

	at org.eclipse.jetty.jsp.JettyJspServlet.service(JettyJspServlet.java:106)

	at javax.servlet.http.HttpServlet.service(HttpServlet.java:790)

	at org.eclipse.jetty.servlet.ServletHolder$NotAsync.service(ServletHolder.java:1450)

	at org.eclipse.jetty.servlet.ServletHolder.handle(ServletHolder.java:799)

	at org.eclipse.jetty.servlet.ServletHandler$ChainEnd.doFilter(ServletHandler.java:1631)

	at org.eclipse.jetty.websocket.server.WebSocketUpgradeFilter.doFilter(WebSocketUpgradeFilter.java:228)

	at org.eclipse.jetty.servlet.FilterHolder.doFilter(FilterHolder.java:193)

	at org.eclipse.jetty.servlet.ServletHandler$Chain.doFilter(ServletHandler.java:1601)

	at org.eclipse.jetty.servlet.ServletHandler.doHandle(ServletHandler.java:548)

	at org.eclipse.jetty.server.handler.ScopedHandler.handle(ScopedHandler.java:143)

	at org.eclipse.jetty.security.SecurityHandler.handle(SecurityHandler.java:600)

	at org.eclipse.jetty.server.handler.HandlerWrapper.handle(HandlerWrapper.java:127)

	at org.eclipse.jetty.server.handler.ScopedHandler.nextHandle(ScopedHandler.java:235)

	at org.eclipse.jetty.server.session.SessionHandler.doHandle(SessionHandler.java:1624)

	at org.eclipse.jetty.server.handler.ScopedHandler.nextHandle(ScopedHandler.java:233)

	at org.eclipse.jetty.server.handler.ContextHandler.doHandle(ContextHandler.java:1434)

	at org.eclipse.jetty.server.handler.ScopedHandler.nextScope(ScopedHandler.java:188)

	at org.eclipse.jetty.servlet.ServletHandler.doScope(ServletHandler.java:501)

	at org.eclipse.jetty.server.session.SessionHandler.doScope(SessionHandler.java:1594)

	at org.eclipse.jetty.server.handler.ScopedHandler.nextScope(ScopedHandler.java:186)

	at org.eclipse.jetty.server.handler.ContextHandler.doScope(ContextHandler.java:1349)

	at org.eclipse.jetty.server.handler.ScopedHandler.handle(ScopedHandler.java:141)

	at org.eclipse.jetty.server.handler.ContextHandlerCollection.handle(ContextHandlerCollection.java:234)

	at org.eclipse.jetty.server.handler.HandlerCollection.handle(HandlerCollection.java:146)

	... 17 more

Caused by: java.lang.ArrayIndexOutOfBoundsException: Index 21 out of bounds for length 19

	at org.unicode.jsp.BidiCharMap.getBidiClass(BidiCharMap.java:84)

	at org.unicode.jsp.BidiCharMap.getBidiClass(BidiCharMap.java:88)

	at org.unicode.jsp.UnicodeUtilities.showBidiLine(UnicodeUtilities.java:1630)

	at org.unicode.jsp.UnicodeUtilities.showBidi(UnicodeUtilities.java:1597)

	at org.unicode.jsp.UnicodeJsp.showBidi(UnicodeJsp.java:37)

	at org.apache.jsp.bidi_jsp._jspService(bidi_jsp.java:278)

	at org.apache.jasper.runtime.HttpJspBase.service(HttpJspBase.java:70)

	at javax.servlet.http.HttpServlet.service(HttpServlet.java:790)

	at org.apache.jasper.servlet.JspServletWrapper.service(JspServletWrapper.java:465)

	... 43 more

[Powered by Jetty:// 9.4.44.v20210927](https://eclipse.org/jetty)

**Comment by markusicu** [comment]
dup of #273
