### ISSUE TITLE
The versioning of ToolUnicodePropertySource is neither tested nor correct

### ISSUE THREAD

**Issue by eggrobin** [unicode-org/unicodetools#484]
Found while digging into the invariants tests, looking at a `U5.0.0:` property:
```
Attempt to reset value for 070F when that is disallowed. Old: Format; New: ALetter


java.lang.UnsupportedOperationException: Attempt to reset value for 070F when that is disallowed. Old: Format; New: ALetter
	at com.ibm.icu.dev.util.UnicodeMap._put(UnicodeMap.java:297)
	at com.ibm.icu.dev.util.UnicodeMap._putAll(UnicodeMap.java:377)
	at com.ibm.icu.dev.util.UnicodeMap.putAll(UnicodeMap.java:436)
	at org.unicode.text.UCD.ToolUnicodePropertySource.(ToolUnicodePropertySource.java:1212)
	at org.unicode.text.UCD.ToolUnicodePropertySource.make(ToolUnicodePropertySource.java:78)
```

The changes made to the derivation of the properties should be gated behind `version`, otherwise we are seeing incorrect old versions in the invariants tests, so we could silently break an invariant by changing the derivation.

We should test that for old versions we generate something consistent with what we published.

**Comment by eggrobin** [comment]
Discussed in the 2023-05-30 meeting: we should test this by comparing IndexUnicodePropertySource against ToolUnicodePropertySource.

**Comment by markusicu** [comment]
Long-term, we should probably drop the older ToolUnicodePropertySource.

**Comment by eggrobin** [comment]
Well, something has to do the derivation if we want derived properties; by design IndexUnicodePropertySource has none of that logic.
